export const RETRIEVE_SPORTS = "RETRIEVE_SPORTS";
export const RETRIEVE_EVENTS = "RETRIEVE_EVENTS";
export const RETRIEVE_OUTCOMES = "RETRIEVE_OUTCOMES";
export const ERROR_SPORTS = "ERROR_SPORTS";
export const ERROR_EVENTS = "ERROR_EVENTS";
export const ERROR_OUTCOMES = "ERROR_OUTCOMES";